name: test

on:
  pull_request:
  push:

jobs:
  test:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: "-test"
      - name: run tests
        run: make test
